### PR TITLE
HotFix + 2.2.0

### PR DESCRIPTION
**Pull request by GuillaumeDIDIER**

### CODE REVIEW

**Comment by GuillaumeDIDIER** [comment]
Should I amend the commit (again), force push and resubmit my pull request ?

**Comment by GuillaumeDIDIER** [comment]
@fishilico ?

**Comment by fishilico** [comment]
I wanted to run some tests before answering because I found that Debian packages python-irc version 8.5.3 (https://packages.debian.org/search?keywords=python-irc) but version >=11.0 is required. It seems that ``python setup.py test`` (which is run by ``debuild``) downloads what is needed, so that the package can be actually built, but anyone who wants to actually use it on a Debian system would need a non-Debian-official package for python-irc (another solution may also consist in Dockerizing kaoz...).

Anyway Gentoo and Arch Linux provides python-irc 11.0.1 so there is no problem there with this new release.

For the git history, I would prefer to keep a linear and "mostly clean" history, but as Kaoz is a small project with only few developers (and owned by the BR), please do as you wish. Also, you may want to update the copyright year in https://github.com/BinetReseau/kaoz/blob/2.1.0/debian/copyright to something like "2013-2015".

Cheers!

**Comment by GuillaumeDIDIER** [comment]
Done

**Comment by fishilico** [comment]
Looks good to me. You can merge this PR and release the new version of Kaoz.

**Comment by GuillaumeDIDIER** [comment]
@Ekleog @Nadrieril @NTag @symphorien @Varal7 Que pensez vous de la PR ?
Merge ou pas merge ?

**Comment by symphorien** [comment]
Si la dépendance c'est ça : https://pypi.python.org/pypi/irc/ alors on peut l'installer via pip sur debian.

**Pull request merged**
